- Formula/portable-openssl.rb
If you'd rather I push these directly instead of opening PRs just let me know!
> openssl: add PPC args

- Abstract/portable-formula.rb
Since Tigerbrew supports using Tiger, suggest building on Tiger instead of Leopard there.
I still need to do some testing on Tiger to make sure all is working smoothly.
> Suggest building on Tiger on PPC

- cmd/brew-portable-package.rb
> portable-package: fix another Linux typo

- Abstract/portable-formula.rb
This replaces the awkward universal arch handling in #16.
Tigerbrew ordinarily builds 32-bit only on 10.4 and 10.5, even on 64-bit hardware. As a result, "universal" builds are still single-arch. The reason for this is that the tooling is unfinished on Tiger, and the linker is fiddly on 10.5, making 64-bit builds an error-prone affair. However, for these portable formulae, I'd love to support i386/ppc universal - that way I can build one binary, on one machine, that works on both Intel and PowerPC. The Apple-provided gcc-4.0 and gcc-4.2 are able to do this on both architectures.
cc @xu-cheng
> portable-formula: enable i386/ppc universal on Tigerbrew

- Formula/portable-git.rb
* Guard macos version check with OS.mac?
* use SHA256
> portable-git various improvement

- Formula/portable-openssl.rb
This adapts a few fixes already in use on Tigerbrew.
> Fix build on 10.4 and i386

- Formula/portable-curl.rb
- Formula/portable-git.rb
- Formula/portable-openssl.rb
- Formula/portable-ruby.rb
- Formula/portable-zlib.rb
- README.md
> Fix broken zlib on Linux

- Formula/portable-curl.rb
- Formula/portable-expat.rb
- Formula/portable-git.rb
- Formula/portable-libyaml.rb
- Formula/portable-ncurses.rb
- Formula/portable-openssl.rb
- Formula/portable-readline.rb
Also add test to improve the formulae.
> Various Version update

- Abstract/portable-formula.rb
I'm guessing this is what you meant, @mistydemeo? I know very little about this though so could be wrong.
> portable-formula: fix (potential?) typo in comment

- Formula/portable-openssl.rb
- README.md
- docker/Dockerfile.arm
- docker/Dockerfile.x86_64
> ARM support

- .travis.yml
> .travis.yml: Add Linux

- .travis.yml
- Formula/portable-berkeley-db.rb
- Formula/portable-libyaml.rb
- Formula/portable-ncurses.rb
- Formula/portable-openssl.rb
- Formula/portable-readline.rb
- Formula/portable-ruby.rb
- Formula/portable-zlib.rb
Also update all dependencies and fix their descriptions.
> portable-ruby 2.3.7

- .travis.yml
- README.md
- docker/Dockerfile.arm
- docker/Dockerfile.x86_64
- Build x86_64 Dockerfile on Travis CI (ARM one is broken)
- Simplify and update README instructions
- Use Debian Wheezy for both Dockerfiles
- Make Dockerfiles more consistent
> Test and fix Dockerfiles

- .gitignore
- azure-pipelines.yml
- docker/Dockerfile.arm
- docker/Dockerfile.x86_64
Fix style of Dockerfile.arm and Dockerfile.x86_64
> Azure: Lint the Dockerfiles

- README.md
Update macOS information and remove stuff no longer supported.
> README: general updates.

- docker/Dockerfile.x86_64
See https://github.com/debuerreotype/docker-debian-artifacts/issues/65
and https://hub.docker.com/r/debian/eol/
> Use docker/eol:wheezy

- .github/workflows/tests.yml
- README.md
These have been broken and unfixed for too long.
CC @sjackman FYI
> Remove ARM builds.

- cmd/portable-package.rb
HOMEBREW_BUILD_BOTTLE was removed.
Fixes #104.
/cc @Bo98
> portable-package: fix building deps as bottles

- .github/workflows/tests.yml
- Abstract/portable-formula.rb
- Formula/portable-ruby.rb
- cmd/portable-package.rb
This should also help debug the current CI failures.
> portable-package: add, use --verbose flag.

- Abstract/portable-formula.rb
- Formula/portable-openssl.rb
- Formula/portable-ruby.rb
- cmd/portable-package.rb
(This doesn't depend on any open `brew` PR.)
> Fix brew style & deprecation error

- Abstract/portable-formula.rb
For https://github.com/Homebrew/brew/pull/10645
> Abstract/portable-formula: fix brew style.

- Abstract/portable-formula.rb
- Dockerfile
- Formula/portable-openssl.rb
Homebrew/mirror will cease tomorrow.
> portable-openssl: update mirror

- .github/workflows/tests.yml
- Dockerfile
- use Homebrew Docker images
- remove some dead/unused code
- cleanup `Dockerfile` `&&` usage
> Fix Debian 7/Wheezy usage

- Dockerfile
Remove some stuff now https://github.com/Homebrew/homebrew-linux-dev/pull/203 is merged.
> Dockerfile: cleanup.

- Abstract/portable-formula.rb
- Formula/portable-ruby.rb
> Portable Ruby 2.6.8 for arm64 macOS

- Formula/portable-ncurses.rb
- Formula/portable-openssl.rb
- Formula/portable-readline.rb
- Formula/portable-zlib.rb
A revision bump to include #149 seems "likely" this month (potentially after a new CI release flow pipeline), so let's do a round of dependency updates.
> Dependency updates

- Formula/portable-openssl.rb
- Formula/portable-zlib.rb
Also add patch for zlib that's in Homebrew/core.
> portable-openssl 1.1.1o

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- README.md
A fully automated release workflow that builds and uploads Portable Ruby bottles from a workflow dispatch event.
The _only_ secrets of our own involved are the BrewTestBot GPG signing keys. Pushing, uploading etc all use the auto-generated GITHUB_TOKEN.
> Add release workflow

- .github/workflows/build.yml
> workflows: migrate Intel runners to ephemeral

- Formula/portable-openssl.rb
- Formula/portable-zlib.rb
Excluding readline, which we might remove in #161.
> Dependency updates (2022-10-25)

- .github/workflows/build.yml
This should allow the build for ARM to succeed at least.
> allow test to run for ruby3 branch

- .github/workflows/build.yml
CI never ran so I didn't see the issue, sorry to bother you again @Bo98
> CI: fix and test build.yml

- Formula/portable-libedit.rb
- Formula/portable-libxcrypt.rb
- Formula/portable-ncurses.rb
- Formula/portable-openssl.rb
- Formula/portable-zlib.rb
Also slim down ncurses install. First three commits were cherry picked from the existing ruby3 branch.
> Dependency updates (2023-09-29)

- Formula/portable-ruby.rb
Needed for https://github.com/Homebrew/brew/pull/16702
> portable-ruby: fix libz requirement for native gems

- .github/workflows/build.yml
- .github/workflows/release.yml
Should be the last ones in our repos.
> workflows: use artifact actions v4

- Formula/portable-ncurses.rb
Needed for https://github.com/Homebrew/homebrew-portable-ruby/pull/190
> portable-ncurses 6.5

- Formula/portable-openssl.rb
Needed for https://github.com/Homebrew/homebrew-portable-ruby/pull/190
> portable-openssl 3.3.0

- Formula/portable-zlib.rb
Needed for https://github.com/Homebrew/homebrew-portable-ruby/pull/190
> portable-zlib 1.3.1

- .github/autobump.txt
- .github/workflows/autobump.yml
Similar workflow as we used in core and cask, set check frequency to daily
relates to #203
> feat: add autobump flow

- Formula/portable-ruby.rb
Might as well get bug fixes while #285 is pending.
> portable-ruby 3.3.8

- Formula/portable-openssl.rb
> portable-openssl: update resource

- .github/workflows/autobump.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
chore(workflows): update default branch for homebrew actions
---
update per default branch name changes
https://github.com/Homebrew/actions/pull/704
> chore(workflows): update default branch for homebrew actions

- .github/workflows/autobump.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- README.md
Fix various references to `master` now this has been done.
See https://github.com/Homebrew/brew/issues/17296
> Migrate default branch to `main`
