docker/Dockerfile

Since Linuxbrew can no longer be run with root privileges, we need to change to the linuxbrew user before running any brew commands.
Fixes #6.

docker: don't run brew as sudo

---

cmd/brew-portable-package.rb

This stops portable-package from working at all on Linux.

portable-package: fix incorrect variable name

---

cmd/brew-portable-package.rb

- Use `xargs` instead of `$(…)` to handle the case where there are zero dependencies.
- Add the `--ignore-dependencies` flag, which was added since this was last updated.

portable-packages: improve dependency uninstallation

---

Abstract/portable-formula.rb
README.md

I followed the convention established by Homebrew/brew@3f9cce0a03e967d2e7bcb7cd16bbc898c1a35708 and left references to specific versions released as "OS X" intact.

OS X → macOS (where appropriate)

---

Formula/portable-git.rb

* Work around Tiger's ld's lack of `-rpath`
* Use gnu-tar to work around quirks in the system tar
* Use portable-expat, since Tiger's expat is only included in X11 (and is very old)
cc @xu-cheng

Fix git on Tiger

---

Formula/portable-readline.rb

The gist this used to use has been taken down, so get the patches directly from GNU.
After this PR is merged, `portable-ruby` should be able to build again on macOS (but not linux).

portable-readline: fix patches

---

Formula/portable-curl.rb
Formula/portable-openssl.rb

They have been handled inside `Abstract/portable-formula.rb`

remove duplicated  ENV.permit_arch_flags

---

README.md

This is adapted from @xu-cheng's table in #1, updated to reflect the presence of 10.4 builds.

README: import "current status"

---

Formula/portable-c-ares.rb
Formula/portable-curl.rb
README.md

Fix portable-c-ares for Linux by linking to c-ares.

portable-curl: fix for Linux

---

Abstract/portable-formula.rb
Formula/portable-ruby@2.2.rb
README.md

This adds a formula for Ruby 2.2, the newest version that currently builds universal when statically linked. Ruby 2.3 and 2.4 currently don't build [due to a bug with statically linked ext](https://bugs.ruby-lang.org/issues/13413). This also includes a patch that scopes the universal workaround to only be applied to `portable-ruby`, not other Ruby versions.
Universal is important for me with Tigerbrew, as I'll want to be shipping a single binary for both PowerPC and Intel. I also prefer shipping a version that's currently supported upstream; 2.0 and 2.1 are both EOL.

Add portable-ruby@2.2

---

Formula/portable-ruby@2.2.rb

* Fix access to the `mcontext` struct, used on Intel, which changed shape between 10.4 and 10.5.
* Fix the universal `CFLAGS` by ensuring GCC doesn't interpret `-march` as an argument to be used when `-arch` is `ppc`.
* Tiger's make (3.80) is too old to understand Ruby's makefile; 3.81 or later is needed.

portable-ruby@2.2: fix build on PPC and Tiger

---

Formula/portable-curl.rb

curl sets `-mmacosx-version-min=10.8` in CFLAGS if not otherwise specified, and since we're overriding CFLAGS, the value set by stdenv gets erased. This does a more conservative replacement, which only strips arch-related flags.

curl: fix replacing CFLAGS

---

Abstract/portable-formula.rb
Formula/portable-curl.rb
Formula/portable-git.rb
Formula/portable-ruby.rb
Formula/portable-ruby@2.2.rb
README.md

* Enable `-Wl,search_paths_first` for all formulae on macOS to prefer to
using our portable static libraries.
* Do not pass `-Wl,search_paths_first` on Linux. It is an invalid flag for
gcc, which always prefers to paths specified by `-L` already.
* Refactor `PortableFormulaMixin#install`.

tweak LDFLAGS

---

Formula/portable-git.rb

Tigerbrew already does this; the version on Tiger is too old to build git, and Leopard's is realistically too old to want to use as well. While CommonCrypto is shipped on Leopard, I trust modern OpenSSL more than I trust 10-year-old CommonCrypto.

portable-git: needs openssl on Tiger/Leopard

---

Formula/portable-openssl.rb

It's possible that we might be building a universal binary on a platform that can't run code for every arch it's building. Examples include:
* Building a ppc/i386 openssl on a PowerPC Mac, which can't run i386 binaries
* Building an i386/x86_64 openssl on an i386 Mac, which can't run x86_64 binaries
openssl's `make test` requires actually running code, so it will fail if run on a platform that can't execute code for the architecture being tested. This uses `Hardware::CPU.can_run?` from Homebrew/brew#2496 to guard `make test` calls.

openssl: don't run `make test` for incompatible archs

---

.travis.yml

Judging from the [Travis docs](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version), this is the oldest OS X/Xcode combo available.

Travis: use oldest available OS X

---

.travis.yml
cmd/brew-portable-package.rb

* Better help message.
* Remove obsoleted ruby version check. Homebrew should always run with
Ruby 2.0+ now. At the same time, old ruby check won't work as it will
just crash when loading formula if Homebrew is somehow run with Ruby
1.8.
* Remove obsoleted HOMEBREW_PREFER_64_BIT. We start to build 32bit formulae
on OS X older than Snow Leopard since 6a3a192a65dfa16636525aa90438e9164ba5e9c0.
* Add new option to not uninstall deps, useful for developing.
* Use `Utils.popen_read` instead of pipe to enforce proper shell esecape.
Otherwise, `brew portable-package some_shell_code_injection` will :boom:.
* Use `brew linkage` on both Mac and Linux. Previously,
`ldd #{f.bin}/#{name.gsub(/^portable-/, "")}` will break for non elf
file.
* Use `safe_system`, instead of superfluous `puts …

rewrite portable-package cmd

---

Formula/portable-ruby@2.3.rb
Formula/portable-ruby@2.4.rb

These were broken due to an [upstream bug](https://bugs.ruby-lang.org/issues/13413) in makefile generation, which prevented the `.rb` portions of statically linked extensions from being installed. This has been fixed in trunk, so I've backported the relevant patch in these formulae and put in a request for it to be backported into the branches upstream.
Trunk, and by extension the upcoming 2.5, is still broken in statically-linked builds for unrelated reasons. I'm looking into the issue.
Having these work will be useful for us since we want to start shipping a vendored Ruby 2.3 when 10.13 is out. :)

Add formulae for portable-ruby 2.3 and 2.4

---

Abstract/portable-formula.rb

Make it lowercase and not end with a period, because
it fits in with the caveats sentece better that way.
Signed-off-by: Bob W. Hogg <rwhogg@linux.com>

Abstract/portable-formula: Tweak keg_only reason

---

Formula/portable-ruby.rb

Fix the error:
```
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

portable-ruby: Add http mirror

---

Formula/portable-openssl.rb

Fix the error:
```
==> Downloading from https://curl.haxx.se/ca/cacert-2017-01-18.pem
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```
Note that http://curl.haxx.se redirects to https://curl.haxx.se

portable-openssl: Add http mirror

---

Formula/portable-ruby.rb
cmd/brew-portable-package.rb

portable-ruby: enable coverage.

---

Formula/portable-ncurses.rb
Formula/portable-openssl.rb
Formula/portable-ruby.rb

Also, while we're here, bump ncurses and openssl.

portable-ruby: match Apple’s Ruby options.

---

Formula/portable-ruby.rb

This should be possible to be required from Ruby (and we need it for https://github.com/Homebrew/brew/pull/3720).

portable-ruby: verify dbm inclusion.

---

Formula/portable-ruby.rb

`ruby` will be linked oportunistically against `libgmp` if it's available when Ruby is configured.

portable-ruby: Add --without-gmp

---

Formula/portable-ruby.rb

This is no longer necessary or valid syntax.

portable-ruby: remove or_later.

---

Abstract/portable-formula.rb
Formula/portable-libyaml.rb
Formula/portable-ncurses.rb
Formula/portable-openssl.rb
Formula/portable-readline.rb
Formula/portable-ruby.rb
Formula/portable-zlib.rb
azure-pipelines.yml
cmd/brew-portable-package.rb
docker/Dockerfile.arm
docker/Dockerfile.x86_64

This will be used to build a new Portable Ruby for Homebrew 2.0.0 on Mavericks.
Should not be merged until Homebrew 2.0.0 will be released imminently.

Deprecate pre-Mavericks.

---

.github/workflows/tests.yml
Formula/portable-libyaml.rb
cmd/brew-portable-package.rb

Installing bottled dependencies requires brewed glibc.
portable-libyaml: Avoid autotools dependency
Fixes #87

portable-package: Install dependencies from source

---

Formula/portable-openssl.rb
Formula/portable-ruby.rb

Ruby 2.6.0 is currently shipped in the macOS 10.15 betas. That might be subject to change.

portable-ruby 2.6.0

---

.github/workflows/tests.yml

These segfault on all supported platforms with Portable Ruby. I'm open to this being fixed but I've spent a bunch of time trying to do so in the past and it doesn't seem to bother non-maintainers.

tests: remove `brew tests`.

---

cmd/portable-package.rb

Make use of new helper from https://github.com/Homebrew/brew/pull/7120. Can't be merged until that PR has been released in a tag.

Use cli/parser min_named helper

---

cmd/portable-package.rb

Use a postfix that fits within our given LineLength.

cmd/portable-package: fix brew style.

---

Formula/portable-libyaml.rb
Formula/portable-ncurses.rb
Formula/portable-openssl.rb
Formula/portable-readline.rb
Formula/portable-ruby.rb

* portable-libyaml 0.2.2 -> 0.2.5
* portable-ncurses 6.1 -> 6.2
- Also removed `dylib` symlinks which did nothing as we don't build dynamic libraries.
* portable-openssl 1.0.2t -> 1.1.1g
- 1.1.x no longer compiles zlib by default for security reasons (CRIME vulnerability). I've switched the formula to respect that.
- Also updated Curl cert bundle to 2020-01-01.
- Added a pkg-config hack to make Ruby link with OpenSSL correctly. Ruby doesn't appear to properly support statically linking OpenSSL sadly, hence the need for the hack.
* portable-readline 8.0.1 -> 8.0.4
- Removed redundant `SHLIB_LIBS` as it is for shared libraries.

Updated dependencies

---

Formula/portable-ruby.rb
README.md

This includes newly-built bottles which should resolve #104 on Linux. The macOS version contains no changes, but was rebuilt so that we can bump the required Ruby revision to `2.6.3_2`.

portable-ruby: bump revision for Linux rebuild

---

cmd/portable-package.rb

Broke after Homebrew/brew#8144.
Also use `safe_popen_read`.

cmd/portable-package: fix for Homebrew.args changes 

---

Dockerfile

Should fix CI failure in #109.

Dockerfile: install pgrep/pkill.

---

cmd/portable-package.rb

`--build-bottle` requires all dependencies to be specified manually.

portable-package: install deps manually.

---

Formula/portable-openssl.rb

update openssl to 1.1.1i, allow building on M1.

portable-openssl: 1.1.1i

---

Formula/portable-ruby.rb

Without this patch, RUBY_PLATFORM returns just `-darwin20` instead of `arm64-darwin20`, which causes issues in `hardware.rb` in brew:
https://github.com/Homebrew/brew/blob/095798be405be47429877f9d92f416153f86e147/Library/Homebrew/hardware.rb#L87-L93
https://github.com/Homebrew/brew/blob/095798be405be47429877f9d92f416153f86e147/Library/Homebrew/hardware.rb#L109-L114
This is included within the generated `configure` script in ruby 2.7.2, but not in 2.7.1, and not in any 2.6.x releases.

portable-ruby: patch to set correct arch on Apple Silicon

---

README.md

Having heard no complaints for months, I think this was indeed fixed by #103 and Homebrew/brew#7718.

README: remove reference to fixed bug

---

Formula/portable-ruby.rb

No-op but may as well upgrade this while I'm here.

portable-ruby: use new bottle format.

---

Formula/portable-ruby.rb
README.md

- Add the `root_url` as it's needed for now to be able to download this (until we don't assume taps are using Bintray).
- Indent `yosemite` hash correctly.
- Add documentation for how to upload bottles.

More GitHub Packages improvements

---

Formula/portable-libyaml.rb
Formula/portable-ncurses.rb
Formula/portable-openssl.rb
Formula/portable-readline.rb
Formula/portable-zlib.rb

Align some formulae with changes made in Homebrew/core (except where differences are intentional).
I've also disabled MD2 support in OpenSSL. This is a legacy protocol and we shouldn't be using this anyway, let alone explicitly enable it.

Dependency updates

---

.github/workflows/tests.yml
Abstract/portable-formula.rb
Formula/portable-libxcrypt.rb
Formula/portable-libyaml.rb
Formula/portable-ncurses.rb
Formula/portable-openssl.rb
Formula/portable-readline.rb
Formula/portable-ruby.rb
README.md

Homebrew 3.5.0 is targetted to drop Yosemite support, so let's drop it here too.
I've set up a temporary CI node to test a 10.11 cross-compile on 10.13 (using 10.11 dev tools: Xcode 7.3.1). Very much an experimental setup but we'll see how it works.
CI changes will be dropped from the PR and I'll do it properly in a subsequent PR.

Bump x86_64 macOS build to use El Capitan

---

.github/workflows/release.yml
Formula/portable-ruby.rb
README.md
cmd/portable-package.rb

It's not worth trying to manage bottle commits (which means turning off CI checks etc.) in the release workflow for what zero users are going to use.
This also reduces the number of secrets required to zero.

Remove bottle block

---

cmd/portable-package.rb

Any macOS < 10.15.6.
This became an issue after I added `brew test-bot --only-cleanup-before` to CI, but not immediately due to download caching.

cmd/portable-package: handle when ca-certificates are required to build

---

Formula/portable-ruby.rb

This regressed when updating CI to Ubuntu 22.04 as it's pulling in paths which only exist on 22.04.

portable-ruby: restore compatibility for older Ubuntu

---

Formula/portable-openssl.rb
Formula/portable-ruby.rb

We set a default `SSL_CERT_FILE` because OpenSSL contains fixed paths baked in that cannot be avoided.
However setting this has the unintended effect of affecting _all_ OpenSSL usages (e.g. in curl) rather than just the one linked into our portable Ruby.
We need to set a `SSL_CERT_FILE` otherwise `open-uri` etc will break, so let's just rename the portable-openssl variable to something different.
https://github.com/Homebrew/brew/issues/14828

Rename SSL_CERT_FILE to avoid overriding system SSL cert file

---

Formula/portable-libedit.rb
Formula/portable-ncurses.rb
Formula/portable-openssl.rb

* [portable-libedit 20221030-3.1](https://github.com/Homebrew/homebrew-portable-ruby/commit/d9d7471468e1bb185c4c801fcd0749de7210ccd0)
* [portable-ncurses 6.4](https://github.com/Homebrew/homebrew-portable-ruby/commit/c19a05453ba603498cb4f32191690aa8befc9fd7)
* [portable-openssl 1.1.1t](https://github.com/Homebrew/homebrew-portable-ruby/commit/4c68437628688a48d90a2316639ff966b20b9898) & bundled certificates

Dependency updates (2023-04-11)

---

.github/workflows/release.yml

workflows/release: use new GITHUB_OUTPUT file

---

Abstract/portable-formula.rb

before:
```
$ brew install homebrew/portable-ruby/portable-ruby
==> Fetching dependencies for homebrew/portable-ruby/portable-ruby: homebrew/portable-ruby/portable-libyaml and homebrew/portable-ruby/portable-openssl
==> Fetching homebrew/portable-ruby/portable-libyaml
==> Downloading https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/2699072/83e7a200-a461-11ea-9884-f4fc06ba83bc?X-Amz-Algo
################################################################################################################################################## 100.0%
==> Fetching homebrew/portable-ruby/portable-openssl
==> Downloading https://curl.se/ca/cacert-2023-08-22.pem …
```

Resolve NoMethodError on brew install

---

Formula/portable-libffi.rb
Formula/portable-openssl.rb
Formula/portable-ruby.rb

Tests for Ruby 3.2.
What I plan for this branch:
* This will be rebased as necessary until all builds pass _and_ the "TEMP: workflow workarounds for ruby3 branch" commit is no longer required (i.e. `brew` itself supports handling of Ruby 3 gems).
* At that point, I'll make it a protected branch and we can make releases from that branch that we can use in `brew`.
* When Ruby 2.6 is killed (i.e. we are sure we will never need to make another Portable Ruby 2.6 release again), then this PR can be merged.
Don't really want to faff around with versioned formulae and adjusting all the workflows to build twice when branches work fine for this purpose, are simpler and make the diff easier to follow.

Ruby 3 working branch

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml

* Remove CI on `master` push. This is a low volume repository so spending an extra 20-25 minutes is a waste of self-hosted resources when we don't allow direct pushes without a pull request. If there's a concern of two simultaneous PRs causing problems only when merged together, we can enable "Require branches to be up to date before merging", which will solve those concerns with minimal annoyance given the PR volume.
* Remove run attempt from ephemeral names as we don't need that anymore.
* Scope permissions slightly more tightly
* Minor cleanup of unused stuff

workflows: various cleanups

---

.github/workflows/build.yml

This sees the final retirement of the non-ephemeral macOS CI.
I've also got a completely recreated 10.11-cross image that is picked up automatically here without any workflow changes but is being tested for the first time with the CI runs in this PR.

workflows/build: use new 11-arm64-cross runner

---

Formula/portable-ruby.rb

We already get rid of the compiler shim references in `rbconfig.rb`, but there are still some more that may not be valid on the target system:
```console
$ brew ruby -e 'p RbConfig::CONFIG.select { |k, v| v.match? /gcc-(.*)-\d+/ }'
{"RANLIB"=>"gcc-ranlib-11", "NM"=>"gcc-nm-11", "AR"=>"gcc-ar-11"}
```
We can replace them with `ranlib`, `nm`, and `ar`, respectively.
This should help to avoid issues like the one spotted in Homebrew/brew#17114.

portable-ruby: fix more compiler toolchain references

---

Formula/portable-libffi.rb

Needed for https://github.com/Homebrew/homebrew-portable-ruby/pull/190

portable-libffi 3.4.6

---

Formula/portable-libyaml.rb

Makes the build slower for no real reason.
Reverts Homebrew/homebrew-portable-ruby#192

Revert "portable-libyaml: move to GitHub tag"

---

README.md

Missed this before so let's add a dedicated heading and hide the manual steps by default.

README: improve release automation visibility.

---

Formula/portable-libffi.rb
Formula/portable-libxcrypt.rb
Formula/portable-libyaml.rb
Formula/portable-openssl.rb
Formula/portable-ruby.rb
Formula/portable-zlib.rb

As discussed in https://github.com/Homebrew/homebrew-portable-ruby/issues/203, this adds `livecheck` blocks to the formulae in this tap. The `portable-ruby` `livecheck` block returns the newest stable version, assuming that the version restriction will be handled in any associated workflow. If we end up needing to handle the version restriction in the `livecheck` block, I can update this or create a follow-up PR.
One other thing worth noting is that the `livecheck` block for `portable-openssl` is checking the latest release on GitHub whereas the formula in homebrew/core checks https://www.openssl.org/source/. Should we align the check with the core formula(e)?

Add livecheck blocks to formulae

---

.github/workflows/autobump.yml

`jq` by default prints newlines but we were using the single-line `GITHUB_OUTPUT` syntax

workflows/autobump: fix list collection

---

.github/workflows/release.yml

Otherwise it defaults to the large merge commit message which is yuck.

workflows/release: set tag title.

---

Abstract/portable-formula.rb
Formula/portable-openssl.rb
Formula/portable-ruby.rb

Thanks to Apple Silicon, testing whether a Portable Ruby builds in a Linux ARM container takes just a few minutes.
* Scope glibc@2.13 reqiurement to Linux only
- This effectively means that ARM support will require glibc 2.35 as a minimum, which seems reasonable to start clean for a new architecture and worry about our glibc formulae later down the line.
* portable-openssl: disable afalgeng
- The test for it seems to fail in aarch64 containers. It might not necessarily will have in a theoretical future CI but it's not a feature we ever use so I opted to disable the feature entirely (Ruby's openssl gem does not allow engines to be enabled when using OpenSSL >=3.0).
- All engines in general are deprecated in OpenSSL itself anyway afaik. Given the Ruby gem dropped support already, maybe we …

Build fixes for ARM

---

cmd/portable-package.rb

While fixing `brew style` tap support (https://github.com/Homebrew/brew/pull/17482), brew CI surfaced some style issues in this tap. This fixes the issues, so brew CI will pass and the fix can be merged.

Fix style issues

---

.github/workflows/release.yml

`shellcheck` is reporting [SC2086](https://www.shellcheck.net/wiki/SC2086) ("Double quote to prevent globbing and word splitting") issues in the `release.yml` workflow. This adds quotes around the related areas to resolve the issues.
There's still one remaining actionlint issue in `build.yml` but it may be a false positive (as described in https://github.com/Homebrew/brew/pull/17482#issuecomment-2163812497):
```
homebrew-portable-ruby/.github/workflows/build.yml:27:16: object, array, and null values should not be evaluated in template with ${{ }} but evaluating the value of type {image: string; options: string} [expression]
|
27 |     container: ${{matrix.container}}
|                ^~~~~~~~~~~~~~~~~~~~~
```
Related to https://github.com/Homebrew/brew/pull/17482

Fix shellcheck issues

---

Formula/portable-ruby.rb

* Remove all bundled gems that we are not using (i.e. everything except `debug`)
* Add a helper file so that we can replace this manual piece of code in Homebrew/brew: https://github.com/Homebrew/brew/blob/c997fa5327571db05bfcf5bd8a54370cf7a8e787/Library/Homebrew/standalone/init.rb#L43-L47 with a `require "portable_ruby_gems"`, which allows bundled gems to used
The functionality introduced here is mostly a nice-to-have for now but it may become very much central to our needs over time. Fiddle will be moved to be a bundled gem in Ruby 3.5.0 which is a gem we need on macOS so this will help with that as normally bundled gems cannot be used in Bundler environments and Fiddle also cannot be vendored in Homebrew/brew due to native extensions.
Relatedly, this system could allow us to include …

portable-ruby: slim bundled gems

---

Formula/portable-ruby.rb

This fixes an issue running `brew install-bundler-gems` on systems without a libcrypt installed.

portable-ruby: ship libcrypt.a

---

Formula/portable-openssl.rb

Bumping to the resource to the latest version.

portable-openssl: update cacert resource

---

.github/dependabot.yml
cmd/portable-package.rb

These were no longer required by default in Homebrew/brew for speed.

cmd/portable-package: add missing requires.

---

Formula/portable-ruby.rb

Under certain circumstances Ruby can hang in a `fork`ed child process with `__psynch_mutexwait` on the ractor scheduler lock.
This is very rare, but seemingly more common on macOS 14 x86_64 for unknown reasons.
Stripe have experienced the same issue on x86_64 Linux and have developed a patch that they are internally using. The patch is public on the Sorbet repository.
The bug appears to be a regression in Ruby 3.3.

portable-ruby: patch to fix rare hang on forking

---

Formula/portable-ruby.rb

As requested in https://github.com/Homebrew/homebrew-portable-ruby/pull/230#discussion_r1701509444

portable-ruby: Add patch PR link

---

cmd/portable-package.rb
cmd/portable-package.rbi

- Part of https://github.com/Homebrew/brew/issues/17297

cmd/portable-package: Enable Sorbet at `typed: strict` level

---

.github/workflows/build.yml

We currently `-ignore` this error, but that's not very ergonomic because
it means you don't get the same results as our CI checks if you run
`actionlint` directly and forget to pass the right `-ignore` flags.
I tried pushing this to #248 but the sync-shared-config workflow keeps
overwriting my fix.

workflows/build: fix actionlint failure

---

.github/workflows/autobump.yml

Align CI setup with what has been done in https://github.com/Homebrew/brew/pull/18704
Use ubuntu-latest when the ubuntu version does not matter.
ubuntu-latest is equivalent to 22.04 right now so this does not change anything
Our ubuntu 22.04 docker image is still used (this has not been modified)

ci: use ubuntu-latest

---

.github/workflows/tests.yml

Fixes https://github.com/Homebrew/homebrew-portable-ruby/security/code-scanning/1
This may not warn anymore on the latest version of `zizmor`, but I would
like to be able to run `zizmor` with `--pedantic`, and that will produce
a warning here.
It's simple enough to avoid, so let's just do that.

workflows/tests: fix `template-injection` warning

---

.github/workflows/build.yml
.github/workflows/release.yml

This helps with transparency and they get updated by Dependabot.

workflows: use full version numbers

---

Formula/portable-openssl.rb

Bumping `cacert` to the latest before we release Portable Ruby 3.4.1

portable-openssl: update resources

---

Formula/portable-openssl.rb

Bumping to the latest `cacert` version.

portable-openssl: bump cacert resource

---

Formula/portable-ruby.rb

Also switches from `pkg-config` to `pkgconf`, so we don't have to keep using the alias.

portable-ruby 3.3.7

---

.github/workflows/build.yml
Abstract/portable-formula.rb
Formula/portable-ruby.rb
cmd/portable-package.rb

Pending changes in brew first.
Bit of a chicken-egg problem given we don't have an arm64 Homebrew Docker image yet so a temporary bootstrap step is required.

Add arm64 CI

---

Formula/portable-zlib.rb

Livecheck is currently returning `Unable to get versions` for this formula's resource. Given that it's a static file that won't be updated, let's skip checking it.

portable-zlib: skip resource livecheck

---

.github/workflows/build.yml

This should no longer be needed.

workflows/build: remove bootstrap steps

---

.github/workflows/autobump.yml
.github/workflows/release.yml

`test-bot` has been merged into Homebrew/brew, so this is no longer necessary and outputs a warning in CI.
---
- https://github.com/Homebrew/brew/pull/20762

workflows: remove `test-bot` Action inputs
